image:
  repository: dreamhunter2333.azurecr.io/notes/notes
  pullPolicy: IfNotPresent
  tag: "v0.0.5"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: notes.dreamhunter2333.com
      serviceName: notes
      portNumber: 80
  tls:
    - hosts:
        - "notes.dreamhunter2333.com"
      secretName: tls-secret

resources:
  requests:
    cpu: 100m
    memory: 100M
  limits:
    cpu: 500m
    memory: 500M

nodeSelector: {}

tolerations: []

affinity: {}
