name: cloudflare pages Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'package.json'
      - 'vuepress.config.js'

jobs:

  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Install and Build
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        yarn && yarn build

    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        command: pages deploy ./docs/.vuepress/dist --project-name=notes --branch production
