name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run: yarn && yarn build
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag registry.cn-beijing.aliyuncs.com/dreamhunter/vuepress-notes:latest
    - name: Push the Docker image
      run: docker push registry.cn-beijing.aliyuncs.com/dreamhunter/vuepress-notes:latest
    - name: Pull and Reboot
      run: apt install expect && expect -c "
          spawn ssh ${{ secrets.ssh_username }}@${{ secrets.ssh_host }} \"${{ secrets.ssh_command }}\"
          expect {
            \"*assword\" {set timeout 300; send \"${{ secrets.ssh_password }}\r\";}
            \"yes/no\" {send \"yes\r\"; exp_continue;}
          }
          expect eof"
