name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run: yarn && yarn build
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag registry.cn-beijing.aliyuncs.com/dreamhunter/vuepress-notes:latest
    - name: Push the Docker image
      run: docker push registry.cn-beijing.aliyuncs.com/dreamhunter/vuepress-notes:latest
    - name: Pull and Reboot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ssh_host }}
        username: ${{ secrets.ssh_username }}
        password: ${{ secrets.ssh_password }}
        port: 22
        script: ${{ secrets.ssh_command }}
