name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install and Build
      run: yarn && yarn build

    - uses: actions/checkout@v3
    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        command: pages deploy ./docs/.vuepress/dist --project-name=notes --branch production
